image: continuumio/miniconda3:latest

before_script:
  - conda env create -f workflow/envs/snakemake-base.yml
  - conda activate snakemake-base

tests:
  state: test
  script:
    - snakemake -n -p --configfile=config/config.json --config  --config genome_config=resources/examples/saccharomyces_cerevisiae.json ensembl_release=98
