image: continuumio/miniconda3:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: one-key-to-rule-them-all
  paths:
    - .conda/
    - .cache/pip/


before_script:
  - export PIP_CACHE_DIR="/opt/cache/pip"
  - conda env create -f workflow/envs/snakemake-base.yml
  - source activate snakemake-base

tests:
  script:
    - echo $ftp_proxy
    - snakemake -n -p --configfile=config/config.json --config  --config genome_config=resources/examples/saccharomyces_cerevisiae.json ensembl_release=98
    - snakemake -p -j2  --keep-target-files --configfile=config/config.json --config --config genome_config=resources/examples/saccharomyces_cerevisiae.json ensembl_release=98
