image: continuumio/miniconda3:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: one-key-to-rule-them-all
  paths:
    - .conda/
    - .cache/pip/


before_script:
  - export PIP_CACHE_DIR="/opt/cache/pip"
  - conda install -c conda-forge mamba
  - mamba create -c conda-forge -c bioconda -n snakemake snakemake=5.30  #conda env create -f workflow/envs/snakemake-base.yml
  - source activate snakemake

test_snakemake:
  script:
    - echo $ftp_proxy
    - snakemake --version
test_pipeline:
  script:
    - snakemake --use-conda -n -p --configfile=config/config.json --config  --config genome_config=resources/examples/saccharomyces_cerevisiae.json ensembl_release=98

run_pipeline:
  script:
    - snakemake --use-conda  -p $CI_SNAKEMAKE_ARGS --configfile=config/config.json --config --config genome_config=resources/examples/saccharomyces_cerevisiae.json ensembl_release=98
