#image: continuumio/miniconda3:latest
image: alpine:3.7

before_script:
  - apk add curl
  - echo "$http_proxy"
  - curl google.de > /dev/null && echo "Internet works"
  - conda env create -f workflow/envs/snakemake-base.yml
  - conda activate snakemake-base

tests:
  script:
    - snakemake -n -p --configfile=config/config.json --config  --config genome_config=resources/examples/saccharomyces_cerevisiae.json ensembl_release=98
