#image: continuumio/miniconda3:latest
image: frolvlad/alpine-miniconda3

before_script:
  - apk add curl
  - echo "$http_proxy"
  - curl google.de > /dev/null && echo "Internet works"
  - conda install -c conda-forge mamba
  - mamba create -c conda-forge -c bioconda -n snakemake snakemake
  - conda activate snakemake-base

tests:
  script:
    - snakemake -n -p --configfile=config/config.json --config  --config genome_config=resources/examples/saccharomyces_cerevisiae.json ensembl_release=98
